name: Continuous Integration
on: [push]
jobs:
  be-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Deps
        run: cd backend && npm i

      - name: Build Step
        run: cd backend && npm run build

      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-cache

      - name: Generate Artifact
        run: cd backend/build && zip -r artifact.zip ./ -x '*.git*'

      - name: Store Artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-artifact
          path: backend/build/artifact.zip

  be-lint:
    name: 🕵️ Lint Backend Code
    needs: [be-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd backend && npm i

      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-cache

      - name: Lint the code
        run: cd backend && npm run lint

  be-test:
    name: 🧪 Backend Unit Tests
    needs: [be-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd backend && npm i && chmod -R a+x node_modules

      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-cache

      - name: Run Unit test
        run: cd backend && npm test

  be-security-audit:
    name: 🛡️ Audit Backend Packages for Security Vulnerabilities
    needs: [ be-build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for security issue
        run: cd backend && npm audit --audit-level=high

  static-analysis:
    name: 🔬 Run Static Analysis on Backend Code
    needs: [ be-build, be-lint, be-test, be-security-audit ]
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
#        with:
#          config-file: ./.github/codeql/codeql.config.yml
#
#      - name: Setup Node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16.x
#
#      - name: Install Deps
#        run: cd backend && npm i
#
#      - name: Build
#        run: cd backend && npm run build