name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - run: cd build
      - run: npm i
      - run: npm run build
